### ISSUE TITLE
[1월 14일] 코드 리뷰 및 회의

### ISSUE THREAD

**Issue by Lulurem** [FRONTENDSCHOOL8/vanilla-project-8#85]
👀 회의 안건

- 노션
1. Progress 기록을 노션에 할지 백로그에 할지 한 곳만 정합시다
2. Schedule 캘린더가 너무 많아서 가독성이 떨어지는 것 같습니다.
    전체 일정 캘린더만 남기고 회의록 등은 Checklist 형태로 두는게 어떠신가요?

- 코드 리뷰
1. 처음부터 끝까지 코드를 읽어주는 방식인지, 각자 읽어보고 궁금한 부분을 물어보는 방식인지?

- PPT
1. 월요일에 꼭 완성해요 😂
2. 각자 맡은 페이지에 대한 설명 5페이지 뒤에 만들어주세요
3. 아쉬웠던 점 적어주세요

- README.md
1. 리드미 작성해주실 분 구합니다

- Validate Local HTML
1. Error 수정 다들 하셨나요

- 마일스톤
1. 3회차를 코딩 이외의 할 일로만 변경하고 기간을 일~월로만 잡으려고 하는데 괜찮을까요?

**Comment by Lulurem** [comment]
- 노션
1. 백로그 번호 17, 18, 19 에 몰아서 체크해 두었음

**Comment by ryujinzz** [comment]
노션
Progress 기록을 노션에 할지 백로그에 할지  -> 백로그로 통일 한 표~! 

전체 일정 캘린더만 남기고 회의록 등은 Checklist 형태로 두는게 어떠신가요? -> 좋습니다. 경민님 수정 부탁드려도 될까요? 

코드 리뷰
처음부터 끝까지 코드를 읽어주는 방식인지, 각자 읽어보고 궁금한 부분을 물어보는 방식인지?

-> js 부분만 코드를 간단하게 소개하고, 궁금한 부분을 물어보는 방식이 좋을 거 같아요~! 
예를 들면  '이 부분은 00기능 구현을 위한 코드입니다. 보다시피 db를 뿌려주는 방식이구요. 궁금한 점 있으실까요? '

Error 수정 -> 딱 한가지 못 했습니다. ;ㅅ; 

마지막에 구현한 장바구니 담는  헤더 기능이 첫 번 째에서 동작하지 않고 두 번 째부터 동작합니다. 
아마 detail.js랑 연동되면서 문제를 일으키는 것 같아서 조금 더 생각해봐야할 것 같습니다.. ㅜㅅㅜ


+) 최종 리팩토링과 배포는 내일 하면 될까요?

**Comment by dlehdg** [comment]
노션
Progress 기록을 노션에 할지 백로그에 할지 한 곳만 정합시다 - 백로그에 한표 넣겠습니다

- 코드 리뷰 -> main 페이지 리뷰 가능합니다

- README.md -> 제가 한번 해봐도 될까요?

- Error 수정 -> 에러는 없지만 마크업 수정이 필요함


마일스톤
3회차를 코딩 이외의 할 일로만 변경하고 기간을 일~월로만 잡으려고 하는데 괜찮을까요? -> 좋은 생각같습니다
